"""initial relational and movement schema"""

from alembic import op
import sqlalchemy as sa

revision = "405e2f264a53"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_definitions",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "patients",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_fictional", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "exercise_assignments",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("therapist_id", sa.String(length=36), nullable=False),
        sa.Column("exercise_definition_id", sa.String(length=36), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_definition_id"],
            ["exercise_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "therapist_patient_access",
        sa.Column("therapist_id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("therapist_id", "patient_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("assignment_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("config_snapshot", sa.JSON(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["exercise_assignments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patient_checkins",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("pain", sa.Integer(), nullable=False),
        sa.Column("effort", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=4000), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "session_devices",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("pairing_hash", sa.String(length=64), nullable=True),
        sa.Column("pairing_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paired", sa.Boolean(), nullable=False),
        sa.Column("last_seq", sa.Integer(), nullable=False),
        sa.Column("clock_offset_ms", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pairing_hash"),
    )
    op.create_index(
        op.f("ix_session_devices_session_id"),
        "session_devices",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "session_metrics",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "session_reports",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("metrics_used", sa.JSON(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "movement_chunks",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("seq_start", sa.Integer(), nullable=False),
        sa.Column("seq_end", sa.Integer(), nullable=False),
        sa.Column("capture_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capture_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("coordinate_system", sa.String(length=40), nullable=False),
        sa.Column("units", sa.String(length=20), nullable=False),
        sa.Column("validity", sa.JSON(), nullable=False),
        sa.Column("frames", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["session_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "seq_start"),
    )
    op.create_index(
        op.f("ix_movement_chunks_session_id"),
        "movement_chunks",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "movement_session_capture",
        "movement_chunks",
        ["session_id", "capture_start"],
        unique=False,
    )
    op.create_table(
        "repetition_events",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("authoritative", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["session_devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "seq", "name"),
    )
    op.create_index(
        op.f("ix_repetition_events_session_id"),
        "repetition_events",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_repetition_events_session_id"), table_name="repetition_events"
    )
    op.drop_table("repetition_events")
    op.drop_index("movement_session_capture", table_name="movement_chunks")
    op.drop_index(op.f("ix_movement_chunks_session_id"), table_name="movement_chunks")
    op.drop_table("movement_chunks")
    op.drop_table("session_reports")
    op.drop_table("session_metrics")
    op.drop_index(op.f("ix_session_devices_session_id"), table_name="session_devices")
    op.drop_table("session_devices")
    op.drop_table("patient_checkins")
    op.drop_table("sessions")
    op.drop_table("therapist_patient_access")
    op.drop_table("exercise_assignments")
    op.drop_table("patients")
    op.drop_table("users")
    op.drop_table("exercise_definitions")
    # ### end Alembic commands ###
